version: 2
jobs:
  build:
    docker:
      - image: geodata/gdal:2.1.3
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install -y python3.4-venv python3-pip python3-setuptools openssh-client git
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --global-option=build_ext --global-option="-I/usr/include/gdal" "GDAL <= `gdal-config --version`"
            python3 setup.py test
