version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install libgdal-dev libgdal1h
            sudo apt-get install python3-gdal
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --global-option=build_ext --global-option="-I/usr/include/gdal" "GDAL <= `gdal-config --version`"
            python setup.py test